export const menuData = {
  mainDishes: [
    {
      name: "רצועות חזה עוף בטריאקי",
      price: 46,
      image: "/images/food/chicken_teriyaki.jpg",
    },
    {
      name: "רצועות חזה עוף שומשום",
      price: 46,
      image: "/images/food/chicken_sesame.jpg",
    },
    {
      name: "רצועות חזה עוף בצ'ילי מתוק",
      price: 46,
      image: "/images/food/chicken_sweet_chili.jpg",
    },
    { name: "עוף בתנור", price: 46, image: "/images/food/roast_chicken.jpg" },
    {
      name: "תבשיל בקר עם ירקות שורש",
      price: 46,
      image: "/images/food/beef_stew.jpg",
    },
    { name: "צלי בקר", price: 46, image: "/images/food/beef_roast.jpg" },
    {
      name: "שניצל ביתי",
      price: 46,
      image: "/images/food/home_made_schnitzel.jpg",
    },
    {
      name: "פלפל ממולא (ימי א')",
      price: 46,
      image: "/images/food/stuffed_peppers.jpg",
    },
    {
      name: "קובה סלק (ימי ב')",
      price: 46,
      image: "/images/food/beet_kuba.jpg",
    },
    { name: "מוסקה (ימי ג')", price: 46, image: "/images/food/moussaka.jpg" },
    {
      name: "כרוב ממולא (ימי ד')",
      price: 46,
      image: "/images/food/stuffed_cabbage.jpg",
    },
    {
      name: "פרגית ממולאת (ימי ה')",
      price: 46,
      image: "/images/food/stuffed_pargiot.jpg",
    },
    {
      name: "פרגיות על האש",
      price: 48,
      image: "/images/food/grilled_pargiot.jpg",
    },
    { name: "כבד על האש", price: 48, image: "/images/food/grilled_liver.jpg" },
    {
      name: "המבורגר על האש",
      price: 48,
      image: "/images/food/grilled_burger.jpg",
    },
    {
      name: "חזה עוף על האש",
      price: 48,
      image: "/images/food/haze_of.jpg",
    },
    { name: "קבב על האש", price: 48, image: "/images/food/grilled_kebab.jpg" },
    {
      name: "אנטריקוט על האש",
      price: 78,
      image: "/images/food/stake.jpg",
    },
    {
      name: "פילה סלמון על הפלנצ'ה",
      price: 66,
      image: "/images/food/salmon_fillet.jpg",
    },
    {
      name: "פילה לברק עם עשבי תיבול על הפלנצ'ה",
      price: 76,
      image: "/images/food/baramundi_fillet.jpg",
    },
    {
      name: "פילה אמנון בתנור יין בן ושום",
      price: 46,
      image: "/images/food/amnon_fillet.jpg",
    },
    {
      name: "מנה צמחונית",
      price: 30,
      image: "/images/food/vegetarian_dish.jpg",
    },
    { name: "מרק היום", price: 28, image: "/images/food/marak.jpg" },
  ],
  hotSides: [
    { name: "אורז", image: "/images/food/rice.jpg" },
    { name: "ירקות מבושלים", image: "/images/food/boiled_vegetables.jpg" },
    { name: "תפוח אדמה אפוי", image: "/images/food/roasted_potatoes.jpg" },
    { name: "פירה", image: "/images/food/mash_potatoes.jpg" },
    { name: "אפונה (ימי א')", image: "/images/food/peas.jpg" },
    { name: "פתיתים (ימי א')", image: "/images/food/pasta.jpg" },
    { name: "שעועית ירוקה (ימי ב')", image: "/images/food/green_beans.jpg" },
    { name: "פסטה פסטו (ימי ב')", image: "/images/food/pesto_pasta.jpg" },
    { name: "קוסקוס (ימי ג')", image: "/images/food/couscous.jpg" },
    { name: "שעועית לבנה (ימי ג')", image: "/images/food/white_beans.jpg" },
    { name: "מג'דרה (ימי ד')", image: "/images/food/mujaddara.jpg" },
    { name: "תירס חם (ימי ד')", image: "/images/food/corn.jpg" },
    { name: "קינואה (ימי ה')", image: "/images/food/quinoa.jpg" },
    { name: "במיה (ימי ה')", image: "/images/food/okra.jpg" },
  ],
  salads: [
    { name: "כרוב עם שמיר", image: "/images/food/cabbage_dill.jpg" },
    {
      name: "סלט ירקות עם טחינה",
      image: "/images/food/salat_thina.jpg",
    },
    { name: "חומוס", image: "/images/food/hummus.jpg" },
    { name: "טחינה", image: "/images/food/tahini.jpg" },
    { name: "מחמצי הבית", image: "/images/food/pickles.jpg" },
    { name: "סלק", image: "/images/food/beetroot.jpg" },
    {
      name: "חצילים בטעמים שונים",
      image: "/images/food/eggplant_varieties.jpg",
    },
    { name: "סלט טורקי", image: "/images/food/turkish_salad.jpg" },
    { name: "סחוג ירוק ביתי", image: "/images/food/home_made_schug.jpg" },
  ],
  drinks: [
    { name: "פחית קוקה קולה", price: 9, image: "/images/drinks/coke.jpeg" },
    { name: "קולה זירו", price: 9, image: "/images/drinks/coke_zero.jpeg" },
    { name: "ספרייט", price: 9, image: "/images/drinks/sprite.jpeg" },
    { name: "ספרייט זירו", price: 9, image: "/images/drinks/sprite_zero.jpeg" },
    { name: "פאנטה", price: 9, image: "/images/drinks/fanta.jpeg" },
    { name: "פיוז טי", price: 9, image: "/images/drinks/fuztea.jpeg" },
    {
      name: "מים בטעמים",
      price: 9,
      image: "/images/drinks/flavored_water.jpeg",
    },
    { name: "בירה שחורה", price: 9, image: "/images/drinks/black_beer.jpeg" },
  ],
};
